# Generated by Django 4.2.11 on 2026-03-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        unique=True, verbose_name="Número da Edição"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateField(verbose_name="Data de Publicação"),
                ),
                (
                    "esta_aberta",
                    models.BooleanField(default=True, verbose_name="Edição em Aberto?"),
                ),
            ],
            options={
                "verbose_name": "Edição",
                "verbose_name_plural": "Edições",
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("conteudo", models.TextField()),
                ("categoria", models.CharField(max_length=100)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "edicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="diario_oficial.edicao",
                    ),
                ),
            ],
        ),
    ]
