# Generated by Django 4.2.11 on 2026-03-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diario_oficial", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materia",
            old_name="categoria",
            new_name="setor",
        ),
    ]
