# Generated by Django 4.2.11 on 2026-03-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diario_oficial", "0002_rename_categoria_materia_setor"),
    ]

    operations = [
        migrations.AddField(
            model_name="edicao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("Ordinária", "Ordinária"),
                    ("Extraordinária", "Extraordinária"),
                    ("Errata", "Errata"),
                ],
                default="Ordinária",
                max_length=20,
                verbose_name="Tipo de Edição",
            ),
        ),
    ]
