# Generated by Django 4.2.11 on 2026-03-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diario_oficial", "0003_edicao_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edicao",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="Número da Edição"
            ),
        ),
    ]
